create or replace TABLE CDC_STRIIM_DB."Strg"."StorageSpace_AUDIT" (
	"StorageSpaceKey" VARCHAR(36) NOT NULL,
	"ParentMiniDrawerTrayModeInternalCode" VARCHAR(10),
	"ParentPendingMiniDrawerTrayModeInternalCode" VARCHAR(10),
	"StorageSpaceShortName" VARCHAR(150),
	"StorageSpaceAbbreviatedName" VARCHAR(100),
	"SortValue" VARCHAR(500),
	"LevelNumber" NUMBER(38,0),
	"FailureInHierarchyFlag" BOOLEAN,
	"DefrostInHierarchyFlag" BOOLEAN,
	"LastAccessedUTCDateTime" TIMESTAMP_NTZ(9),
	"LastAccessedLocalDateTime" TIMESTAMP_NTZ(9),
	"LastModifiedDispensingDeviceKey" VARCHAR(36),
	"LastModifiedUTCDateTime" TIMESTAMP_NTZ(9),
	"LastModifiedBinaryValue" BINARY(8388608),
	OPERATION_NAME VARCHAR(200),
	HOSTNAME VARCHAR(200),
	TS VARCHAR(200),
	SEQ VARCHAR(200),
	TABLE_NAME VARCHAR(200)
);

create or replace TABLE CDC_STRIIM_DB."Strg"."StorageSpaceItem_AUDIT" (
	"StorageSpaceItemKey" VARCHAR(36) NOT NULL,
	"StorageSpaceKey" VARCHAR(36),
	"ItemKey" VARCHAR(36),
	"AssociationUTCDateTime" TIMESTAMP_NTZ(9),
	"AssociationLocalDateTime" TIMESTAMP_NTZ(9),
	"DisassociationUTCDateTime" TIMESTAMP_NTZ(9),
	"DisassociationLocalDateTime" TIMESTAMP_NTZ(9),
	"DispensingDeviceEjectWithInventoryFlag" BOOLEAN,
	"LastDispenseUTCDateTime" TIMESTAMP_NTZ(9),
	"LastDispenseLocalDateTime" TIMESTAMP_NTZ(9),
	"LastInventoryUTCDateTime" TIMESTAMP_NTZ(9),
	"LastInventoryLocalDateTime" TIMESTAMP_NTZ(9),
	"LastLoadRefillUTCDateTime" TIMESTAMP_NTZ(9),
	"LastLoadRefillLocalDateTime" TIMESTAMP_NTZ(9),
	"LastLoadRefillSuccessfulScanFlag" BOOLEAN,
	"LastLoadRefillActorKey" VARCHAR(36),
	"LastRxCheckUTCDateTime" TIMESTAMP_NTZ(9),
	"LastRxCheckLocalDateTime" TIMESTAMP_NTZ(9),
	"LoadUTCDateTime" TIMESTAMP_NTZ(9),
	"LoadLocalDateTime" TIMESTAMP_NTZ(9),
	"LastKnownUTCDateTime" TIMESTAMP_NTZ(9),
	"LastKnownLocalDateTime" TIMESTAMP_NTZ(9),
	"PendedAtServerFlag" BOOLEAN,
	"LastModifiedDispensingDeviceKey" VARCHAR(36),
	"AssociationActorKey" VARCHAR(36),
	"DisassociationActorKey" VARCHAR(36),
	"LastModifiedUTCDateTime" TIMESTAMP_NTZ(9),
	"LastModifiedBinaryValue" BINARY(8388608),
	OPERATION_NAME VARCHAR(200),
	HOSTNAME VARCHAR(200),
	TS VARCHAR(200),
	SEQ VARCHAR(200),
	TABLE_NAME VARCHAR(200)
);

create or replace TABLE CDC_STRIIM_DB."Tx"."StorageItemTransaction_AUDIT" (
	"StorageItemTransactionKey" VARCHAR(36),
	"ItemTransactionKey" VARCHAR(36),
	"StartUTCDateTime" TIMESTAMP_NTZ(9),
	"StartLocalDateTime" TIMESTAMP_NTZ(9),
	"EndUTCDateTime" TIMESTAMP_NTZ(9),
	"EndLocalDateTime" TIMESTAMP_NTZ(9),
	"DispensingDeviceKey" VARCHAR(36),
	"DispensingDeviceSnapshotKey" VARCHAR(36),
	"StorageSpaceKey" VARCHAR(36),
	"StorageSpaceSnapshotKey" VARCHAR(36),
	"Level2StorageSpaceSnapshotKey" VARCHAR(36),
	"Level1StorageSpaceSnapshotKey" VARCHAR(36),
	"Level0StorageSpaceSnapshotKey" VARCHAR(36),
	"StorageSpaceItemSnapshotKey" VARCHAR(36),
	"StorageSpaceItemKey" VARCHAR(36),
	"StartStorageSpaceInventoryKey" VARCHAR(36),
	"EndStorageSpaceInventoryKey" VARCHAR(36),
	"ManuallyVerifiedStorageSpaceFlag" BOOLEAN,
	"StorageSpaceShortName" VARCHAR(150),
	"StorageSpaceAbbreviatedName" VARCHAR(100),
	"EndTotalInventoryQuantity" NUMBER(14,4),
	"ParentStorageSpaceSnapshotKey" VARCHAR(36),
	"ParentStorageSpaceShortName" VARCHAR(150),
	"ParentEndTotalInventoryQuantity" NUMBER(14,4),
	"MobileFlag" BOOLEAN,
	"InsertFlag" BOOLEAN,
	"EjectFlag" BOOLEAN,
	"StorageSpaceDisconnectFlag" BOOLEAN,
	"InsertUncheckedCUBIEFlag" BOOLEAN,
	"CUBIEAnotherDestinationFlag" BOOLEAN,
	"UnloadReasonInternalCode" VARCHAR(10),
	"UnloadReasonFreeText" VARCHAR(500),
	"LocationFreeText" VARCHAR(500),
	"LastModifiedDispensingDeviceKey" VARCHAR(36),
	"LastModifiedActorKey" VARCHAR(36),
	"LastModifiedUTCDateTime" TIMESTAMP_NTZ(9),
	"LastModifiedBinaryValue" BINARY(8388608),
	OPERATION_NAME VARCHAR(200),
	HOSTNAME VARCHAR(200),
	TS VARCHAR(200),
	SEQ VARCHAR(200),
	TABLE_NAME VARCHAR(200)
);
