-- TABLE NAME - HcOrder.PharmacyOrderSnapshot
CREATE TABLE HcOrder.PharmacyOrderSnapshot
(
    "PharmacyOrderSnapshotKey"             varchar(36) NOT NULL,
    "PharmacyOrderKey"                     varchar(36) NOT NULL,
    "StartUTCDateTime"                     datetime    NOT NULL,
    "StartLocalDateTime"                   datetime    NOT NULL,
    "EndUTCDateTime"                       timestamp,
    "EndLocalDateTime"                     timestamp,
    "ExternalSystemKey"                    varchar(36) NOT NULL,
    "EncounterKey"                         varchar(36) NOT NULL,
    "PharmacyOrderID"                      VARCHAR(50) NOT NULL,
    "DiscontinuedFlag"                     BOOLEAN     NOT NULL,
    "CancelledFlag"                        BOOLEAN     NOT NULL,
    "HoldEffectiveUTCDateTime"             timestamp,
    "HoldEffectiveLocalDateTime"           timestamp,
    "HoldEffectiveDateOnlyFlag"            BOOLEAN     NOT NULL,
    "ReleaseHoldEffectiveUTCDateTime"      timestamp,
    "ReleaseHoldEffectiveLocalDateTime"    timestamp,
    "ReleaseHoldEffectiveDateOnlyFlag"     BOOLEAN     NOT NULL,
    "CancelledUTCDateTime"                 timestamp,
    "CancelledLocalDateTime"               timestamp,
    "GiveItemKey"                          varchar(36),
    "GiveID"                               VARCHAR(50),
    "GiveDescriptionText"                  VARCHAR(250),
    "GiveAmount"                           numeric(14, 4),
    "MaximumGiveAmount"                    numeric(14, 4),
    "GiveUOMKey"                           varchar(36),
    "GiveExternalUOMKey"                   varchar(36),
    "DispenseQuantity"                     numeric(14, 4),
    "PharmacyOrderTypeInternalCode"        VARCHAR(10),
    "InboundWarningFlag"                   BOOLEAN     NOT NULL,
    "SchedulePersistableFlag"              BOOLEAN     NOT NULL,
    "DispenseNotUsingDispensingDeviceFlag" BOOLEAN     NOT NULL,
    "FromExternalSystemFlag"               BOOLEAN     NOT NULL,
    "FirstSnapshotFlag"                    BOOLEAN     NOT NULL,
    "LastModifiedActorKey"                 varchar(36),
    "LastModifiedUTCDateTime"              datetime    NOT NULL,
    "LastModifiedBinaryValue"              timestamp   NOT NULL,
    PRIMARY KEY ("PharmacyOrderSnapshotKey")
);
