-- TABLE NAME - HcOrder.PharmacyOrderSnapshot
CREATE OR REPLACE TABLE "HcOrder"."PharmacyOrderSnapshot"
(
    "PharmacyOrderSnapshotKey"             VARCHAR(36), -- NOT NULL,
    "PharmacyOrderKey"                     VARCHAR(36), -- NOT NULL,
    "StartUTCDateTime"                     DATETIME,    -- NOT NULL,
    "StartLocalDateTime"                   DATETIME,    -- NOT NULL,
    "EndUTCDateTime"                       DATETIME,
    "EndLocalDateTime"                     DATETIME,
    "ExternalSystemKey"                    VARCHAR(36), -- NOT NULL,
    "EncounterKey"                         VARCHAR(36), -- NOT NULL,
    "PharmacyOrderID"                      VARCHAR(50), -- NOT NULL,
    "DiscontinuedFlag"                     BOOLEAN,     -- NOT NULL,
    "CancelledFlag"                        BOOLEAN,     -- NOT NULL,
    "HoldEffectiveUTCDateTime"             DATETIME,
    "HoldEffectiveLocalDateTime"           DATETIME,
    "HoldEffectiveDateOnlyFlag"            BOOLEAN,     -- NOT NULL,
    "ReleaseHoldEffectiveUTCDateTime"      DATETIME,
    "ReleaseHoldEffectiveLocalDateTime"    DATETIME,
    "ReleaseHoldEffectiveDateOnlyFlag"     BOOLEAN,     -- NOT NULL,
    "CancelledUTCDateTime"                 DATETIME,
    "CancelledLocalDateTime"               DATETIME,
    "GiveItemKey"                          VARCHAR(36),
    "GiveID"                               VARCHAR(50),
    "GiveDescriptionText"                  VARCHAR(250),
    "GiveAmount"                           NUMERIC(14, 4),
    "MaximumGiveAmount"                    NUMERIC(14, 4),
    "GiveUOMKey"                           VARCHAR(36),
    "GiveExternalUOMKey"                   VARCHAR(36),
    "DispenseQuantity"                     NUMERIC(14, 4),
    "PharmacyOrderTypeInternalCode"        VARCHAR(10),
    "InboundWarningFlag"                   BOOLEAN,     -- NOT NULL,
    "SchedulePersistableFlag"              BOOLEAN,     -- NOT NULL,
    "DispenseNotUsingDispensingDeviceFlag" BOOLEAN,     -- NOT NULL,
    "FromExternalSystemFlag"               BOOLEAN,     -- NOT NULL,
    "FirstSnapshotFlag"                    BOOLEAN,     -- NOT NULL,
    "LastModifiedActorKey"                 VARCHAR(36),
    "LastModifiedUTCDateTime"              DATETIME,    -- NOT NULL,
    "LastModifiedBinaryValue"              VARBINARY,   -- NOT NULL,
    PRIMARY KEY ("PharmacyOrderSnapshotKey")
);
