# This is a basic workflow to help you get started with Actions

name: sf_deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ddl_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Copy files
        uses: actions/checkout@v3
        
      - name: Check copied files
        run: ls -la
        
      - run: cat README.md
          
